version: "3"
services:
  collectd1:
    build:
      context: ./collectd
      dockerfile: Dockerfile
    container_name: collect1
  collectd2:
    build:
      context: ./collectd
      dockerfile: Dockerfile
    container_name: collect2
  influxdb:
    build:
      context: ./influxdb
      dockerfile: Dockerfile
    container_name: influx
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826"
    environment: 
      - INFLUXDB_DB=collectd
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
