version: '3'
services:
  myreg:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./registry/conf/config.yml:/etc/docker/registry/config.yml
      - ./registry/storage:/var/lib/registry:rw
