# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.5"
    config.vm.synced_folder "./", "/var/www"
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.define "tomcat1" do |tomcat1|
    tomcat1.vm.hostname = "tomcat1"
    tomcat1.vm.network "private_network", ip: "192.168.33.11"
    tomcat1.vm.provision :shell, :path => "bootstrap_tomcat1.sh" 
  end

  config.vm.define "tomcat2" do |tomcat2|
    tomcat2.vm.hostname = "tomcat2"
    tomcat2.vm.network "private_network", ip: "192.168.33.12"
    tomcat2.vm.provision :shell, :path => "bootstrap_tomcat2.sh"
  end

  config.vm.define "balancer" do |balancer|
    balancer.vm.hostname = "balancer"
    balancer.vm.network "private_network", ip: "192.168.33.10"
    balancer.vm.network "forwarded_port", guest: 80, host: 20080
    balancer.vm.provision :shell, :path => "bootstrap_balancer.sh" 
  end

end
