# -*- mode: ruby -*-
# vi: set ft=ruby :

$mach_quant = 3

Vagrant.configure("2") do |config|

	config.vm.box = "bento/centos-7.5"
		config.vm.synced_folder "./", "/var/www"
		config.ssh.username = "vagrant"
		config.ssh.password = "vagrant"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "512"
	end

(1..$mach_quant).each do |i|
    config.vm.define "tomcat#{i}" do |tomcat|
        tomcat.vm.network "private_network", ip: "192.168.1.#{24+i}"
        tomcat.vm.hostname = "worker#{i}"
	tomcat.vm.provision :shell, :path => "bootstrap_tomcat.sh" 
    end
end  
  
	config.vm.define "balancer" do |balancer|
		balancer.vm.hostname = "balancer"
		balancer.vm.network "private_network", ip: "192.168.1.10"
		balancer.vm.network "forwarded_port", guest: 80, host: 20080
		balancer.vm.provision :shell, :path => "bootstrap_balancer.sh" 
	end

end
