default['apache']['username'] = 'jenkins'
default['apache']['shell'] = '/bin/bash/'
default['apache']['path_to_mod'] = '/home/vagrant/modjk.sh'
default['apache']['path_to_workers'] = '/etc/httpd/conf/workers.properties'
default['apache']['path_to_conf'] = '/etc/httpd/conf/httpd.conf'