# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

	config.vm.box = "bento/centos-7.5"
	config.vm.synced_folder "./", "/vagrant"
	config.ssh.username = "vagrant"
	config.ssh.password = "vagrant"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "512"
	end

	config.vm.define "server1" do |server1|
		server1.vm.hostname = "server1"
		server1.vm.network "private_network", ip: "192.168.33.10"
		server1.vm.provision :shell, :path => "bootstrap_server1.sh"
	end
	
	
	config.vm.define "server2" do |server2|
		server2.vm.hostname = "server2"
		server2.vm.network "private_network", ip: "192.168.33.11"
		server2.vm.provision :shell, :path => "bootstrap_server2.sh"  
	end

	
end