# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

config.vm.box = "bento/centos-7.5"

config.vm.provider "virtualbox" do |vb|
vb.memory = "512"
end

config.vm.define "server1" do |server1|
  server1.vm.hostname = "server1"
  server1.vm.network "private_network", ip: "192.168.33.10"
  
server1.vm.provision "shell", inline: <<-SHELL
sudo echo "192.168.33.11 server2" >> /etc/hosts
sudo yum install git -y
git clone https://github.com/ig0r0k/DevOps.git
cd ./DevOps/
sudo git checkout  task2
cat ./task2/test.txt
SHELL
end

config.vm.define "server2" do |server2|
  server2.vm.hostname = "server2"
  server2.vm.network "private_network", ip: "192.168.33.11"
  
server2.vm.provision "shell", inline: <<-SHELL
sudo echo "192.168.33.10 server1" >> /etc/hosts
SHELL
end

end
